steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pharma-assistant:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/pharma-assistant:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pharma-assistant:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pharma-assistant:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pharma-assistant-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pharma-assistant:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/pharma-assistant:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/pharma-assistant:latest'

timeout: '1200s'